//AUTHENTICATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_ERROR";

export const SIGNOUT = "SIGNOUT";


//MOVIES
export const ADD_MOVIE_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_ITEM_ERROR";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

