export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";


export const ADD_MOVIE_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_ITEM_ERROR";
